-- Empty 2 tables with foreign key
ALTER TABLE Countries NOCHECK CONSTRAINT ALL;
ALTER TABLE Cities NOCHECK CONSTRAINT ALL;
DELETE FROM Countries;
DELETE FROM Cities;
ALTER TABLE Countries CHECK CONSTRAINT ALL;
ALTER TABLE Cities CHECK CONSTRAINT ALL;

-- reset index
DBCC CHECKIDENT ('Countries', RESEED, 0);
DBCC CHECKIDENT ('Cities', RESEED, 0);